apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-s3-ingress
  namespace: seaweedfs
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-system-retry@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - s3.scigames.at
    secretName: wildcard-scigames
  rules:
  - host: s3.scigames.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seaweedfs-s3
            port:
              number: 8333
