apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-vip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.11.70.50/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-vip-pool
