apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-system-retry@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vault.scigames.at
    secretName: wildcard-scigames
  rules:
  - host: vault.scigames.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-ha
            port:
              number: 8200
