kind: Secret
apiVersion: v1
metadata:
  name: snipeit-secrets
  namespace: snipeit
  annotations:
    avp.kubernetes.io/path: "kv/data/argocd"
type: Opaque
stringData:
  APP_KEY: <APP_KEY>
  # mysql-password: test123
  # mysql-root-password: test123
  # MYSQL_USER: snipeit-user
  # MYSQL_DATABASE: snipeit-db-test
  MYSQL_PASSWORD: snipeit-pw-test
  # MYSQL_PORT_3306_TCP_ADDR: snipeit-mysql
  # MYSQL_PORT_3306_TCP_PORT: "3306"
    
